#!/bin/bash

### BEGIN INIT INFO
# Provides:           lunr-screen
# Required-Start:     $local_fs $remote_fs
# Required-Stop:      $local_fs $remote_fs
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  lunr-screen
# Description:        Start a screen session with the specified screenrc
### END INIT INFO

DESC="Lunr Screen Session"
NAME="lunr-screen"
SCREENRC="/etc/lunr/lunr.screenrc"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

start ()
{
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --start -c vagrant --exec /usr/bin/screen -- -dm -c $SCREENRC
}

stop ()
{
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    PID=`ps -ef | grep $SCREENRC | grep SCREEN | grep -v grep | awk '{print $2}'`
    kill $PID 
}

case "$1" in

  start)
      start
        ;;
  stop)
      stop
      ;;

  restart)
      stop
      start
      ;;
  *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
      ;;
esac
exit 0
